version: '3'

volumes:
  mysql-data:

services:
  workbench:
    build: .
    ports:
      - "3000:3000"
    restart: always
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=
    ports:
      - "8080:80"
    restart: always
