version: '3'

services:
  rails:
    build: .
    environment:
      - USER_NAME
      - USER_ID
      - GROUP_ID
    volumes:
      - .:/project
    working_dir: /project
    ports:
      - "3000:3000"
    restart: always
