version: '3'

services:
  rails:
    build: .
    user: "${UID}:${GID}"
    volumes:
      - .:/project
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    tmpfs:
      - /project/tmp
    working_dir: /project
    ports:
      - "3000:3000"
    restart: always
